<?php return array (
  'email_type' => '1',
  'email_safe' => '',
  'mail_address' => '',
  'smtp' => '',
  'smtp_user' => '',
  'smtp_pwd' => '',
  'smtp_port' => '',
  'order_by' => 'new',
  'name' => 'iWebShop开源商城系统',
  'url' => 'http://www.aircheng.com',
  'master' => '',
  'qq' => '',
  'email' => '',
  'mobile' => '',
  'phone' => '',
  'address' => '',
  'site_footer_code' => '<div class="footer" style="text-align:center"><p class="links"><a href="">关于我们</a>|<a href="">常见问题</a>|<a href="">安全交易</a>|<a href="">购买流程</a>|<a href="">如何付款</a>|<a href="">联系我们</a>|<a href="">合作提案</a></p><p class="copyright">Powered by <a href="https://www.aircheng.com" title="b2b2c商城系统">iWebShop商城系统</a></p>Copyright © 2005-2021 <a class="copyys" target="_blank" href="https://beian.miit.gov.cn/">鲁ICP备XXXXXXXX号</a></div>',
  'tax' => '10',
  'stockup_time' => '1',
  'index_seo_title' => 'iWebShop开源商城系统',
  'index_seo_keywords' => '开源商城系统,开源网店系统,php商城系统,php商城源码,多用户商城系统,微信商城系统',
  'index_seo_description' => 'iWebShop是一款基于PHP语言及MYSQL数据库开发的B2B2C多用户商城系统，支持自营和多商家入驻、集成微信商城、手机商城、移动端APP商城、三级分销、电商直播、微信小程序，它可以承载大数据量且性能优良，代码支持二次开发是电商建站首选。',
  'goods_no_pre' => 'SD',
  'commission' => '1',
  'store_num_warning' => '1',
  'reg_option' => '0',
  'low_withdraw' => '1',
  'low_bill' => '0',
)?>